### ISSUE TITLE
[BUG] at Log out button

### ISSUE THREAD

**Issue by dqcode** [Capstone-campyuk/QE-CAMPYUK-WEB_AUTOMATION#4]

**Comment by dqcode** [comment]
log out button seringkali tidak konsisten dalam fungsi nya

**Comment by irfanfitriandi** [comment]
sudah difix mas

**Comment by diahrdn** [comment]
https://user-images.githubusercontent.com/116274338/218354267-b9794be5-7166-4e10-9b69-08b3f2c8da35.mov
