### ISSUE TITLE
[BUG] Host add camp without choose image

### ISSUE THREAD

**Issue by diahrdn** [Capstone-campyuk/QE-CAMPYUK-WEB_AUTOMATION#5]
**Background:**
Given host already at campyuk website
And host already logged in

**Steps**
When host directed in Dashboard host 
And host click Add Camp button
Then host directed in addcamp page
And host input Title as <title>, Price as <price>, Description as <description>, drag marker location, City as <city>, Address blank data, choose business license, and Distance as <numberDistance>
And host can't click Add Camp button

**Actual Result**
Add Camp button is enabled but the camp not posted

**Expected Result**
Add Camp button is disabled

**Comment by irfanfitriandi** [comment]
sudah difix ya mba thanks

**Comment by diahrdn** [comment]
![Image](https://user-images.githubusercontent.com/116274338/218355357-68b0313c-670c-4a9b-8c79-5120d6af2d59.png)
