### ISSUE TITLE
[BUG] List camp on Dashboard Host after Login

### ISSUE THREAD

**Issue by diahrdn** [Capstone-campyuk/QE-CAMPYUK-WEB_AUTOMATION#6]
Setelah Host berhasil melakukan login
Dan Host belum pernah melakukan "Add Camp"
Dan tampilan Dashboard Host kosong dari list camp

**Actual Result**
After Login, Dashboard menampilkan list camp
Host merefresh page untuk menampilkan dashboard host sebenarnya

**Expected Result**
After Login, Dashboard host tidak menampilkan list camp

**Comment by irfanfitriandi** [comment]
siap mba ini problemnya masi sama ko dengan yang ditulis mas diqy (log out), perihal cookie, nanti solvednya sekalian, thanks mba

**Comment by irfanfitriandi** [comment]
sudah difix ya mba thanks

**Comment by diahrdn** [comment]
https://user-images.githubusercontent.com/116274338/218355768-b1ea998f-a76b-49db-b3bb-18f25ceca1d4.mov
