### ISSUE TITLE
[BUG] host add item

### ISSUE THREAD

**Issue by diahrdn** [Capstone-campyuk/QE-CAMPYUK-WEB_AUTOMATION#7]
**Bckground**
Given host already at campyuk website
And host already logged in

**Steps**
When host already in Dashboard page
And host click edit button
Then host already in Edit Camp page
And host click add item
And host input Name, price stok
And host click Add Item button
Then host should see an success message "successful add item"
And click OK button on alert

**Actual Result**
host doesn't see the success message after add item
Item not added successfully

**Exepcted Result**
host see the success message after add item
Item added successfully

**Comment by irfanfitriandi** [comment]
has been fixed

**Comment by diahrdn** [comment]
https://user-images.githubusercontent.com/116274338/218356769-e8a217b2-03bc-4b81-bf83-35f0c6f7d800.mov
