### ISSUE TITLE
[BUG] host input alphabet field price on add item

### ISSUE THREAD

**Issue by diahrdn** [Capstone-campyuk/QE-CAMPYUK-WEB_AUTOMATION#8]
**Background**
Given host already at campyuk website
And host already logged in

**Steps**
When host already in Dashboard page
And host click edit button
Then host already in Edit Camp page
And host click add item
And host can't input alphabet in field price

**Actual Result**
host can input "e" in field price

**Expected Result**
host can input number in field price
not allowed to input alphabet, characters, ect

**Comment by irfanfitriandi** [comment]
has been fixed

**Comment by diahrdn** [comment]
https://user-images.githubusercontent.com/116274338/218357053-ab78ae9f-6e1f-44dc-a007-201e826b9929.mov
